Q1 = 'how many apples in a dozen apples'
Q2 = 'What is the color of the sky on a clear day?'
Q3 = 'How many legs does a dog have?'
Q4 = 'What is 2 + 2?'
Q5 = 'What do you call the frozen form of water?'
Q6 = 'What is the opposite of "hot"?'
Q7 = 'What animal goes "meow"?'
Q8 = 'What fruit is typically red and often associated with doctors?'
Q9 = 'How many days are in a week?'
Q10 = 'What is the first letter of the alphabet?'

